#version 430
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct StructuredInput
{
    vec3 Position;
    uint Reserved;
    uint Normal;
    uint Tangent;
    uint UV;
    uint Color;
};

struct OutputData
{
    vec3 Position;
    uint Normal;
    uint Tangent;
    uint Color;
    uint Padding0;
    uint Padding1;
};

layout(set = 2, binding = 1, std430) readonly buffer Input
{
    StructuredInput _data[];
} Input_1;

layout(set = 2, binding = 0, std430) buffer Output
{
    OutputData _data[];
} Output_1;

void _main(uvec3 dtid)
{
    StructuredInput _input;
    _input.Position = Input_1._data[dtid.x].Position;
    _input.Reserved = Input_1._data[dtid.x].Reserved;
    _input.Normal = Input_1._data[dtid.x].Normal;
    _input.Tangent = Input_1._data[dtid.x].Tangent;
    _input.UV = Input_1._data[dtid.x].UV;
    _input.Color = Input_1._data[dtid.x].Color;
    OutputData _output;
    _output.Position = _input.Position + vec3(1.0, 2.0, 3.0);
    _output.Normal = _input.Normal;
    _output.Tangent = _input.Tangent;
    _output.Color = (_input.Color ^ _input.UV) ^ _input.Reserved;
    _output.Padding0 = 0u;
    _output.Padding1 = 0u;
    Output_1._data[dtid.x].Position = _output.Position;
    Output_1._data[dtid.x].Normal = _output.Normal;
    Output_1._data[dtid.x].Tangent = _output.Tangent;
    Output_1._data[dtid.x].Color = _output.Color;
    Output_1._data[dtid.x].Padding0 = _output.Padding0;
    Output_1._data[dtid.x].Padding1 = _output.Padding1;
}

void main()
{
    uvec3 dtid = gl_GlobalInvocationID;
    uvec3 param = dtid;
    _main(param);
}

