#version 430
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct SlotData
{
    vec3 Position;
    uint Direction;
};

struct OutputData
{
    vec3 Position;
    uint Direction;
    uint Checksum;
    uint Padding0;
    uint Padding1;
    uint Padding2;
};

layout(set = 2, binding = 1, std430) readonly buffer Data
{
    SlotData _data[];
} Data_1;

layout(set = 2, binding = 0, std430) buffer Output
{
    OutputData _data[];
} Output_1;

void _main(uvec3 dtid)
{
    uint index = dtid.x;
    SlotData data;
    data.Position = Data_1._data[index].Position;
    data.Direction = Data_1._data[index].Direction;
    OutputData _output;
    _output.Position = data.Position + vec3(10.0, 20.0, 30.0);
    _output.Direction = data.Direction;
    _output.Checksum = data.Direction ^ (index * 16843009u);
    _output.Padding0 = 0u;
    _output.Padding1 = 0u;
    _output.Padding2 = 0u;
    Output_1._data[index].Position = _output.Position;
    Output_1._data[index].Direction = _output.Direction;
    Output_1._data[index].Checksum = _output.Checksum;
    Output_1._data[index].Padding0 = _output.Padding0;
    Output_1._data[index].Padding1 = _output.Padding1;
    Output_1._data[index].Padding2 = _output.Padding2;
}

void main()
{
    uvec3 dtid = gl_GlobalInvocationID;
    uvec3 param = dtid;
    _main(param);
}

