#version 430
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct InputA
{
    vec3 Values;
    uint Tag;
};

struct InputB
{
    uint X;
    uint Y;
    uint Z;
    uint W;
};

struct OutputA
{
    float Value;
    uint Tag;
    uint Mix;
    uint Padding;
};

struct OutputB
{
    vec3 Values;
    uint Checksum;
};

layout(set = 2, binding = 1, std430) readonly buffer Input1
{
    InputA _data[];
} Input1_1;

layout(set = 2, binding = 2, std430) readonly buffer Input2
{
    InputB _data[];
} Input2_1;

layout(set = 2, binding = 0, std430) buffer Output0
{
    OutputA _data[];
} Output0_1;

layout(set = 2, binding = 3, std430) buffer Output3
{
    OutputB _data[];
} Output3_1;

void _main(uvec3 dtid)
{
    uint index = dtid.x;
    InputA a;
    a.Values = Input1_1._data[index].Values;
    a.Tag = Input1_1._data[index].Tag;
    InputB b;
    b.X = Input2_1._data[index].X;
    b.Y = Input2_1._data[index].Y;
    b.Z = Input2_1._data[index].Z;
    b.W = Input2_1._data[index].W;
    uint _mix = (((a.Tag ^ b.X) ^ b.Y) ^ b.Z) ^ b.W;
    OutputA outA;
    outA.Value = ((a.Values.x + a.Values.y) + a.Values.z) + float(b.X & 255u);
    outA.Tag = a.Tag;
    outA.Mix = _mix;
    outA.Padding = 0u;
    Output0_1._data[index].Value = outA.Value;
    Output0_1._data[index].Tag = outA.Tag;
    Output0_1._data[index].Mix = outA.Mix;
    Output0_1._data[index].Padding = outA.Padding;
    OutputB outB;
    outB.Values = a.Values * vec3(2.0, 3.0, 4.0);
    outB.Checksum = _mix + index;
    Output3_1._data[index].Values = outB.Values;
    Output3_1._data[index].Checksum = outB.Checksum;
}

void main()
{
    uvec3 dtid = gl_GlobalInvocationID;
    uvec3 param = dtid;
    _main(param);
}

