#version 430
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct SlotData
{
    vec3 Position;
    uint Direction;
};

layout(set = 2, binding = 1, std430) buffer Data
{
    SlotData _data[];
} Data_1;

void _main(uvec3 dtid)
{
    uint index = dtid.x;
    SlotData data;
    data.Position = vec3((float(index) * 2.0) + 0.25, (float(index) * (-3.0)) + 0.5, (float(index) * 4.0) - 0.75);
    data.Direction = 305397760u + (index * 31u);
    Data_1._data[index].Position = data.Position;
    Data_1._data[index].Direction = data.Direction;
}

void main()
{
    uvec3 dtid = gl_GlobalInvocationID;
    uvec3 param = dtid;
    _main(param);
}

