diagnostic(off, derivative_uniformity);

struct StructuredInput {
  Position : vec3<f32>,
  Reserved : u32,
  Normal : u32,
  Tangent : u32,
  UV : u32,
  Color : u32,
}

struct Input {
  m : array<StructuredInput>,
}

@group(2) @binding(1) var<storage, read> Input_1 : Input;

struct OutputData {
  Position : vec3<f32>,
  Normal : u32,
  Tangent : u32,
  Color : u32,
  Padding0 : u32,
  Padding1 : u32,
}

struct Output {
  m_1 : array<OutputData>,
}

@group(2) @binding(0) var<storage, read_write> Output_1 : Output;

@compute @workgroup_size(1u, 1u, 1u)
fn main(@builtin(global_invocation_id) dtid : vec3<u32>) {
  var dtid_1 : vec3<u32>;
  var param : vec3<u32>;
  dtid_1 = dtid;
  param = dtid_1;
  v(&(param));
}

struct StructuredInput_1 {
  Position : vec3<f32>,
  Reserved : u32,
  Normal : u32,
  Tangent : u32,
  UV : u32,
  Color : u32,
}

struct OutputData_1 {
  Position : vec3<f32>,
  Normal : u32,
  Tangent : u32,
  Color : u32,
  Padding0 : u32,
  Padding1 : u32,
}

fn v(dtid : ptr<function, vec3<u32>>) {
  var input : StructuredInput_1;
  var output : OutputData_1;
  let v_1 = Input_1.m[(*(dtid)).x];
  input.Position = v_1.Position;
  input.Reserved = v_1.Reserved;
  input.Normal = v_1.Normal;
  input.Tangent = v_1.Tangent;
  input.UV = v_1.UV;
  input.Color = v_1.Color;
  output.Position = (input.Position + vec3<f32>(1.0f, 2.0f, 3.0f));
  output.Normal = input.Normal;
  output.Tangent = input.Tangent;
  output.Color = ((input.Color ^ input.UV) ^ input.Reserved);
  output.Padding0 = 0u;
  output.Padding1 = 0u;
  let v_2 = (*(dtid)).x;
  let v_3 = output;
  let v_4 = &(Output_1.m_1[v_2]);
  (*(v_4)).Position = v_3.Position;
  (*(v_4)).Normal = v_3.Normal;
  (*(v_4)).Tangent = v_3.Tangent;
  (*(v_4)).Color = v_3.Color;
  (*(v_4)).Padding0 = v_3.Padding0;
  (*(v_4)).Padding1 = v_3.Padding1;
}
