#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SlotData
{
    float3 Position;
    uint Direction;
};

struct SlotData_1
{
    packed_float3 Position;
    uint Direction;
};

struct Data
{
    SlotData_1 _data[1];
};

struct OutputData
{
    float3 Position;
    uint Direction;
    uint Checksum;
    uint Padding0;
    uint Padding1;
    uint Padding2;
};

struct OutputData_1
{
    packed_float3 Position;
    uint Direction;
    uint Checksum;
    uint Padding0;
    uint Padding1;
    uint Padding2;
};

struct Output
{
    OutputData_1 _data[1];
};

static inline __attribute__((always_inline))
void _main(thread const uint3& dtid, const device Data& Data_1, device Output& Output_1)
{
    uint index = dtid.x;
    SlotData data;
    data.Position = float3(Data_1._data[index].Position);
    data.Direction = Data_1._data[index].Direction;
    OutputData _output;
    _output.Position = data.Position + float3(10.0, 20.0, 30.0);
    _output.Direction = data.Direction;
    _output.Checksum = data.Direction ^ (index * 16843009u);
    _output.Padding0 = 0u;
    _output.Padding1 = 0u;
    _output.Padding2 = 0u;
    Output_1._data[index].Position = _output.Position;
    Output_1._data[index].Direction = _output.Direction;
    Output_1._data[index].Checksum = _output.Checksum;
    Output_1._data[index].Padding0 = _output.Padding0;
    Output_1._data[index].Padding1 = _output.Padding1;
    Output_1._data[index].Padding2 = _output.Padding2;
}

kernel void main0(device Output& Output_1 [[buffer(10)]], const device Data& Data_1 [[buffer(11)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint3 dtid = gl_GlobalInvocationID;
    uint3 param = dtid;
    _main(param, Data_1, Output_1);
}

