#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct StructuredInput
{
    float3 Position;
    uint Reserved;
    uint Normal;
    uint Tangent;
    uint UV;
    uint Color;
};

struct StructuredInput_1
{
    packed_float3 Position;
    uint Reserved;
    uint Normal;
    uint Tangent;
    uint UV;
    uint Color;
};

struct Input
{
    StructuredInput_1 _data[1];
};

struct OutputData
{
    float3 Position;
    uint Normal;
    uint Tangent;
    uint Color;
    uint Padding0;
    uint Padding1;
};

struct OutputData_1
{
    packed_float3 Position;
    uint Normal;
    uint Tangent;
    uint Color;
    uint Padding0;
    uint Padding1;
};

struct Output
{
    OutputData_1 _data[1];
};

static inline __attribute__((always_inline))
void _main(thread const uint3& dtid, const device Input& Input_1, device Output& Output_1)
{
    StructuredInput _input;
    _input.Position = float3(Input_1._data[dtid.x].Position);
    _input.Reserved = Input_1._data[dtid.x].Reserved;
    _input.Normal = Input_1._data[dtid.x].Normal;
    _input.Tangent = Input_1._data[dtid.x].Tangent;
    _input.UV = Input_1._data[dtid.x].UV;
    _input.Color = Input_1._data[dtid.x].Color;
    OutputData _output;
    _output.Position = _input.Position + float3(1.0, 2.0, 3.0);
    _output.Normal = _input.Normal;
    _output.Tangent = _input.Tangent;
    _output.Color = (_input.Color ^ _input.UV) ^ _input.Reserved;
    _output.Padding0 = 0u;
    _output.Padding1 = 0u;
    Output_1._data[dtid.x].Position = _output.Position;
    Output_1._data[dtid.x].Normal = _output.Normal;
    Output_1._data[dtid.x].Tangent = _output.Tangent;
    Output_1._data[dtid.x].Color = _output.Color;
    Output_1._data[dtid.x].Padding0 = _output.Padding0;
    Output_1._data[dtid.x].Padding1 = _output.Padding1;
}

kernel void main0(device Output& Output_1 [[buffer(10)]], const device Input& Input_1 [[buffer(11)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint3 dtid = gl_GlobalInvocationID;
    uint3 param = dtid;
    _main(param, Input_1, Output_1);
}

