#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SPIRV_Cross_Input
{
    uint3 _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID;
};

struct TransformData
{
    uint _data[1];
};

static inline __attribute__((always_inline))
void StoreTransform(thread const uint& index, thread const float3& translation, device TransformData& TransformData_1)
{
    uint base = index * 80u;
    int byteAddrTemp = int((base + 0u) >> uint(2));
    TransformData_1._data[byteAddrTemp] = 1u;
    int byteAddrTemp_1 = int((base + 4u) >> uint(2));
    TransformData_1._data[byteAddrTemp_1] = index;
    int byteAddrTemp_2 = int((base + 8u) >> uint(2));
    TransformData_1._data[byteAddrTemp_2] = as_type<uint>(0.0);
    int byteAddrTemp_3 = int((base + 12u) >> uint(2));
    TransformData_1._data[byteAddrTemp_3] = 0u;
    int byteAddrTemp_4 = int((base + 16u) >> uint(2));
    TransformData_1._data[byteAddrTemp_4] = 0u;
    int byteAddrTemp_5 = int((base + 20u) >> uint(2));
    TransformData_1._data[byteAddrTemp_5] = 0u;
    int byteAddrTemp_6 = int((base + 24u) >> uint(2));
    TransformData_1._data[byteAddrTemp_6] = 0u;
    TransformData_1._data[byteAddrTemp_6 + 1] = 0u;
    int byteAddrTemp_7 = int((base + 32u) >> uint(2));
    TransformData_1._data[byteAddrTemp_7] = as_type<uint>(1.0);
    int byteAddrTemp_8 = int((base + 36u) >> uint(2));
    TransformData_1._data[byteAddrTemp_8] = as_type<uint>(0.0);
    int byteAddrTemp_9 = int((base + 40u) >> uint(2));
    TransformData_1._data[byteAddrTemp_9] = as_type<uint>(0.0);
    int byteAddrTemp_10 = int((base + 44u) >> uint(2));
    TransformData_1._data[byteAddrTemp_10] = as_type<uint>(translation.x);
    int byteAddrTemp_11 = int((base + 48u) >> uint(2));
    TransformData_1._data[byteAddrTemp_11] = as_type<uint>(0.0);
    int byteAddrTemp_12 = int((base + 52u) >> uint(2));
    TransformData_1._data[byteAddrTemp_12] = as_type<uint>(1.0);
    int byteAddrTemp_13 = int((base + 56u) >> uint(2));
    TransformData_1._data[byteAddrTemp_13] = as_type<uint>(0.0);
    int byteAddrTemp_14 = int((base + 60u) >> uint(2));
    TransformData_1._data[byteAddrTemp_14] = as_type<uint>(translation.y);
    int byteAddrTemp_15 = int((base + 64u) >> uint(2));
    TransformData_1._data[byteAddrTemp_15] = as_type<uint>(0.0);
    int byteAddrTemp_16 = int((base + 68u) >> uint(2));
    TransformData_1._data[byteAddrTemp_16] = as_type<uint>(0.0);
    int byteAddrTemp_17 = int((base + 72u) >> uint(2));
    TransformData_1._data[byteAddrTemp_17] = as_type<uint>(1.0);
    int byteAddrTemp_18 = int((base + 76u) >> uint(2));
    TransformData_1._data[byteAddrTemp_18] = as_type<uint>(translation.z);
}

static inline __attribute__((always_inline))
void StoreAttribute(thread const uint& index, thread const float2& offset, thread const float& scale, thread const uint& colorTag, device TransformData& AttributeData)
{
    uint base = index * 16u;
    int byteAddrTemp = int((base + 0u) >> uint(2));
    AttributeData._data[byteAddrTemp] = as_type<uint2>(offset).x;
    AttributeData._data[byteAddrTemp + 1] = as_type<uint2>(offset).y;
    int byteAddrTemp_1 = int((base + 8u) >> uint(2));
    AttributeData._data[byteAddrTemp_1] = as_type<uint>(scale);
    int byteAddrTemp_2 = int((base + 12u) >> uint(2));
    AttributeData._data[byteAddrTemp_2] = colorTag;
}

static inline __attribute__((always_inline))
void _main(thread const uint3& dtid, device TransformData& TransformData_1, device TransformData& AttributeData)
{
    uint index = dtid.x;
    if (index == 0u)
    {
        uint param = index;
        float3 param_1 = float3(-0.550000011920928955078125, -0.119999997317790985107421875, 0.0);
        StoreTransform(param, param_1, TransformData_1);
        uint param_2 = index;
        float2 param_3 = float2(0.0500000007450580596923828125);
        float param_4 = 0.85000002384185791015625;
        uint param_5 = 0u;
        StoreAttribute(param_2, param_3, param_4, param_5, AttributeData);
    }
    else
    {
        if (index == 1u)
        {
            uint param_6 = index;
            float3 param_7 = float3(0.0);
            StoreTransform(param_6, param_7, TransformData_1);
            uint param_8 = index;
            float2 param_9 = float2(0.0);
            float param_10 = 0.64999997615814208984375;
            uint param_11 = 1u;
            StoreAttribute(param_8, param_9, param_10, param_11, AttributeData);
        }
        else
        {
            if (index == 2u)
            {
                uint param_12 = index;
                float3 param_13 = float3(0.550000011920928955078125, 0.119999997317790985107421875, 0.0);
                StoreTransform(param_12, param_13, TransformData_1);
                uint param_14 = index;
                float2 param_15 = float2(-0.0500000007450580596923828125);
                float param_16 = 0.449999988079071044921875;
                uint param_17 = 2u;
                StoreAttribute(param_14, param_15, param_16, param_17, AttributeData);
            }
        }
    }
}

static inline __attribute__((always_inline))
void comp_main(device TransformData& TransformData_1, device TransformData& AttributeData, thread uint3& _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID)
{
    uint3 dtid = _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID;
    uint3 param = dtid;
    _main(param, TransformData_1, AttributeData);
}

static inline __attribute__((always_inline))
void _main(thread const SPIRV_Cross_Input& stage_input, device TransformData& TransformData_1, device TransformData& AttributeData, thread uint3& _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID)
{
    _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID = stage_input._RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID;
    comp_main(TransformData_1, AttributeData, _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID);
}

kernel void main0(device TransformData& TransformData_1 [[buffer(10)]], device TransformData& AttributeData [[buffer(11)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    SPIRV_Cross_Input stage_input;
    stage_input._RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID = gl_GlobalInvocationID;
    SPIRV_Cross_Input param = stage_input;
    uint3 _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID;
    _main(param, TransformData_1, AttributeData, _RESERVED_IDENTIFIER_FIXUP_gl_GlobalInvocationID);
}

