#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SlotData
{
    float3 Position;
    uint Direction;
};

struct SlotData_1
{
    packed_float3 Position;
    uint Direction;
};

struct Data
{
    SlotData_1 _data[1];
};

static inline __attribute__((always_inline))
void _main(thread const uint3& dtid, device Data& Data_1)
{
    uint index = dtid.x;
    SlotData data;
    data.Position = float3((float(index) * 2.0) + 0.25, (float(index) * (-3.0)) + 0.5, (float(index) * 4.0) - 0.75);
    data.Direction = 305397760u + (index * 31u);
    Data_1._data[index].Position = data.Position;
    Data_1._data[index].Direction = data.Direction;
}

kernel void main0(device Data& Data_1 [[buffer(11)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint3 dtid = gl_GlobalInvocationID;
    uint3 param = dtid;
    _main(param, Data_1);
}

