#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct StructuredMatrixRecord
{
    uint Flags;
    float Age;
    uint2 Packed;
    float4x3 Transform;
    float3 Direction;
    uint Color;
};

struct StructuredMatrixRecord_1
{
    uint Flags;
    float Age;
    uint2 Packed;
    float3x4 Transform;
    packed_float3 Direction;
    uint Color;
};

struct Records
{
    StructuredMatrixRecord_1 _data[1];
};

struct StructuredMatrixOutput
{
    float3 Translation;
    uint Flags;
    float3 Direction;
    uint Color;
    float3 Axis0;
    uint Checksum;
};

struct StructuredMatrixOutput_1
{
    packed_float3 Translation;
    uint Flags;
    packed_float3 Direction;
    uint Color;
    packed_float3 Axis0;
    uint Checksum;
};

struct Output
{
    StructuredMatrixOutput_1 _data[1];
};

static inline __attribute__((always_inline))
void _main(thread const uint3& dtid, const device Records& Records_1, device Output& Output_1)
{
    StructuredMatrixRecord record;
    record.Flags = Records_1._data[dtid.x].Flags;
    record.Age = Records_1._data[dtid.x].Age;
    record.Packed = Records_1._data[dtid.x].Packed;
    record.Transform = transpose(Records_1._data[dtid.x].Transform);
    record.Direction = float3(Records_1._data[dtid.x].Direction);
    record.Color = Records_1._data[dtid.x].Color;
    StructuredMatrixOutput _output;
    _output.Translation = record.Transform[3];
    _output.Flags = record.Flags ^ as_type<uint>(record.Age);
    _output.Direction = record.Direction + (record.Transform[2] * 0.25);
    _output.Color = record.Color;
    _output.Axis0 = (record.Transform[0] * record.Age) + record.Direction;
    _output.Checksum = ((record.Flags ^ record.Packed.x) ^ record.Packed.y) ^ record.Color;
    Output_1._data[dtid.x].Translation = _output.Translation;
    Output_1._data[dtid.x].Flags = _output.Flags;
    Output_1._data[dtid.x].Direction = _output.Direction;
    Output_1._data[dtid.x].Color = _output.Color;
    Output_1._data[dtid.x].Axis0 = _output.Axis0;
    Output_1._data[dtid.x].Checksum = _output.Checksum;
}

kernel void main0(device Output& Output_1 [[buffer(10)]], const device Records& Records_1 [[buffer(11)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint3 dtid = gl_GlobalInvocationID;
    uint3 param = dtid;
    _main(param, Records_1, Output_1);
}

